version: '3'


services:
  db:
    container_name: blog-db
    image: mariadb:10.11.6
    volumes:
      - blog-vol:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  phpmyadmin:
    container_name: phpmyadmin
    links:
      - db 
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
volumes:
  blog-vol:
    external: false